### ISSUE TITLE
User Submissions by Text Input

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#73]
### Problem/Why
Currently, users cannot create a new submission without uploading a file. This can create an obstacle for submitters who would rather compose or paste text directly into a textarea to submit a manuscript to be reviewed in the application.

### Goal/What
Enable a user to be able to paste text into an input, submit it, and have their text saved to the system as a new submission.

### Solution/How
Create a form that accepts text for a submission.  Write functionality to save the submission in the database and associate the submission to the user as the submitter.

### To Do / Acceptance Criteria

- [x] Update backend to accept text for a submission creation
- [x] Create/modify Vue template(s)
- [x] Add PHPUnit testing to verify the submission creation API works as expected

### Review Checklist

- [ ] A user can create a submission by just pasting text into a textarea
- [ ] The resulting submission is saved in the database and assocated with a user 

### Accessibility Checklist

- [ ] The submission form can be used solely by a keyboard
- [ ] No new accessibility violations are introduced

**Comment by gmeben** [comment]
It would seem that the description of this issue is a bit out of date, as most of its concerns have already been addressed. 

However, the ability to copy-paste text into an input or textarea to establish the content of a submission (in the place of the file of a submission) has not yet been addressed.

I recommend re-writing the description once we review this as a team and reach a consensus on how to proceed with this issue.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/73?planning-poker) with Zenhub @gmeben @vilagshe @wreality
