### ISSUE TITLE
User registration from external source

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#88]
**Problem/Why**

Users may enjoy the option to create their account using a federated account (Google, Github, Facebook, Twitter, etc). Currently, registration on the application is only localized to CCR.

---

**Goal/What**

Users should be presented with social login/account creation buttons when creating an account.  This should extract useful/pertinent information from that federated account (email, name, etc) and copy it into their CCR account.

---

**Solution/How**

Laravel Socialite should take care of this.

Utilize OAuth 2.0 workflows for account creation.  The end goal should be to make it relatively painless to integrate any OAuth 2.0 compliant federated login provider.

--- 

### To Do 
- [x] Leverage Laravel OAuth implementation to create a reusable OAuth account creation flow. 
- [x] Document the addition of additional federated login providers 
- [x] Implement account creation from ORCID out of the box.
- [x] Implement account creation from Google out of the box.

### Review Checklist 
- [ ] Users can create an account on the application via ORCID and Google authentication providers. 
- [ ] Developer documentation for addition of new federated providers is created 
- [ ] Appropriate unit tests are added such that code coverage does not decrease (or a decrease can be explained) 
- [ ] Any needed user-facing documentation is complete 
- [ ] Any needed admin-facing documentation is complete 
 
## Attachments 
 
- [Is child to System User Registration](https://trello.com/c/99N2A9ZC/15-system-user-registration#sf-dependencies&dependencyType=is_child_to&dependencyId=5f6a0648f52b64894091a375&resolved=false) 
 
> Trello Source: https://trello.com/c/GVTKSYxd

**Comment by gmeben** [comment]
This looks related to https://app.zenhub.com/workspaces/ccr-5ff39ba363391e0019713c87/issues/mesh-research/ccr/85

**Comment by sattler9** [comment]
Connected to user request https://feedback.pilcrow.dev/posts/1/allow-users-to-login-create-accounts-using-google-and-orcid

**Comment by gmeben** [comment]
I've found that the work I'm currently doing in #85 is also overlapping with this issue, which means I've technically been working on this already.

**Comment by gmeben** [comment]
> Leverage Laravel OAuth implementation to create a reusable OAuth account creation flow.

I'm going to interpret this step as referring to Socialite as that's the official OAuth implementation in Laravel. Sociliate has been installed and is being used to handle OAuth so I'm considering this step as complete.

> Document the addition of additional federated login providers

At the moment we're planning on supporting ORCID and Google specifically, but we're planning on implementing this in a way that does not dictate what providers are supported by default in Pilcrow. We will likely continue to use SocialiteProviders for this. We're thinking about using a plugin-style architecture so that developers maintaining their own instances of Pilcrow can choose what providers to support themselves.

This means should documentation be written for this, it should be minimal and should be limited to user-focused documentation, because the technical implementation of this feature is likely going to change drastically for developers. It would be best not to have to invest in a lot of copyediting work if it's just going to become undone soon.

>  Implement Google, Facebook, Twitter account creation out of the box.

For our initial release, ORCID and Google are the providers we plan on supporting at first. At this point, Twitter is no longer being considered for our instance of Pilcrow given what has transpired over the past 3 years since this issue was originally created. Given [what HCommons has published about Facebook/Meta](https://team.hcommons.org/2023/12/15/threads/), I think it's also safe to say it's no longer being considered either.

This is a minor wording issue but this task also implies that accounts are being created on the providers when account creation is actually taking place in Pilcrow.

For these reasons, I think this task should be rewritten as: "Implement account creation from Google and ORCID out of the box."
